apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zul9y39wl-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zul9y39wl-dotnet-basic-gitops