apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zul9y39wl-dotnet-basic
  janus-idp.io/tekton: zul9y39wl-dotnet-basic
  backstage.io/kubernetes-id: zul9y39wl-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zul9y39wl-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
